pipeline {
    agent any

    stages {
        stage('Git clone') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'master', url: 'https://github.com/julianooen/DevOpsTema16.git'
            }
        }
        stage('Run Docker-compose') {
            steps {
                // Run docker-compose.
                sh "docker-compose up -d"
            }
        }
        stage('Test') {
            steps{
                
                sh 'mvn gatling:test'
                gatlingArchive()
                
            }
        }
    }
}
